export { default as HomeLayout } from './HomeLayout';
export { default as Landing } from './Landing';
export { default as Tienda } from './Tienda';
export { default as Recetas } from './Recetas';
export { default as PuntosDeVenta } from './PuntosDeVenta';
export { default as Blog } from './Blog';
export { default as Carrito } from './Carrito';
export { default as Login } from './Login';
export { default as Register } from './Register';
